/*
 * This file is generated by jOOQ.
 */
package eu.dissco.core.digitalspecimenprocessor.database.jooq;


import eu.dissco.core.digitalspecimenprocessor.database.jooq.tables.DigitalMediaObject;
import eu.dissco.core.digitalspecimenprocessor.database.jooq.tables.DigitalSpecimen;
import eu.dissco.core.digitalspecimenprocessor.database.jooq.tables.SourceSystem;
import java.util.Arrays;
import java.util.List;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

  /**
   * The table <code>public.digital_media_object</code>.
   */
  public final DigitalMediaObject DIGITAL_MEDIA_OBJECT = DigitalMediaObject.DIGITAL_MEDIA_OBJECT;

    /**
     * The table <code>public.digital_specimen</code>.
     */
    public final DigitalSpecimen DIGITAL_SPECIMEN = DigitalSpecimen.DIGITAL_SPECIMEN;

    /**
     * The table <code>public.source_system</code>.
     */
    public final SourceSystem SOURCE_SYSTEM = SourceSystem.SOURCE_SYSTEM;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            DigitalMediaObject.DIGITAL_MEDIA_OBJECT,
            DigitalSpecimen.DIGITAL_SPECIMEN,
            SourceSystem.SOURCE_SYSTEM
        );
    }
}
