/*
 * This file is generated by jOOQ.
 */
package eu.dissco.core.digitalspecimenprocessor.database.jooq;


import eu.dissco.core.digitalspecimenprocessor.database.jooq.tables.DigitalMediaObject;
import eu.dissco.core.digitalspecimenprocessor.database.jooq.tables.DigitalSpecimen;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Tables {

    /**
     * The table <code>public.digital_media_object</code>.
     */
    public static final DigitalMediaObject DIGITAL_MEDIA_OBJECT = DigitalMediaObject.DIGITAL_MEDIA_OBJECT;

    /**
     * The table <code>public.digital_specimen</code>.
     */
    public static final DigitalSpecimen DIGITAL_SPECIMEN = DigitalSpecimen.DIGITAL_SPECIMEN;
}
