/*
 * This file is generated by jOOQ.
 */
package eu.dissco.core.digitalspecimenprocessor.database.jooq.enums;


import eu.dissco.core.digitalspecimenprocessor.database.jooq.Public;
import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum AnnotationStatusEnum implements EnumType {

    ACCEPTED("ACCEPTED"),

    MERGED("MERGED"),

    PENDING("PENDING"),

    REJECTED("REJECTED"),

    TOMBSTONED("TOMBSTONED");

    private final String literal;

    private AnnotationStatusEnum(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "annotation_status_enum";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static AnnotationStatusEnum lookupLiteral(String literal) {
        return EnumType.lookupLiteral(AnnotationStatusEnum.class, literal);
    }
}
