/*
 * This file is generated by jOOQ.
 */
package eu.dissco.core.digitalspecimenprocessor.database.jooq.tables;


import eu.dissco.core.digitalspecimenprocessor.database.jooq.Indexes;
import eu.dissco.core.digitalspecimenprocessor.database.jooq.Keys;
import eu.dissco.core.digitalspecimenprocessor.database.jooq.Public;
import eu.dissco.core.digitalspecimenprocessor.database.jooq.tables.records.DigitalSpecimenRecord;

import java.time.Instant;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function14;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DigitalSpecimen extends TableImpl<DigitalSpecimenRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.digital_specimen</code>
     */
    public static final DigitalSpecimen DIGITAL_SPECIMEN = new DigitalSpecimen();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DigitalSpecimenRecord> getRecordType() {
        return DigitalSpecimenRecord.class;
    }

    /**
     * The column <code>public.digital_specimen.id</code>.
     */
    public final TableField<DigitalSpecimenRecord, String> ID = createField(DSL.name("id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.digital_specimen.version</code>.
     */
    public final TableField<DigitalSpecimenRecord, Integer> VERSION = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.digital_specimen.type</code>.
     */
    public final TableField<DigitalSpecimenRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.digital_specimen.midslevel</code>.
     */
    public final TableField<DigitalSpecimenRecord, Short> MIDSLEVEL = createField(DSL.name("midslevel"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.digital_specimen.physical_specimen_id</code>.
     */
    public final TableField<DigitalSpecimenRecord, String> PHYSICAL_SPECIMEN_ID = createField(DSL.name("physical_specimen_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.digital_specimen.physical_specimen_type</code>.
     */
    public final TableField<DigitalSpecimenRecord, String> PHYSICAL_SPECIMEN_TYPE = createField(DSL.name("physical_specimen_type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.digital_specimen.specimen_name</code>.
     */
    public final TableField<DigitalSpecimenRecord, String> SPECIMEN_NAME = createField(DSL.name("specimen_name"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.digital_specimen.organization_id</code>.
     */
    public final TableField<DigitalSpecimenRecord, String> ORGANIZATION_ID = createField(DSL.name("organization_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.digital_specimen.source_system_id</code>.
     */
    public final TableField<DigitalSpecimenRecord, String> SOURCE_SYSTEM_ID = createField(DSL.name("source_system_id"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.digital_specimen.created</code>.
     */
    public final TableField<DigitalSpecimenRecord, Instant> CREATED = createField(DSL.name("created"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.digital_specimen.last_checked</code>.
     */
    public final TableField<DigitalSpecimenRecord, Instant> LAST_CHECKED = createField(DSL.name("last_checked"), SQLDataType.INSTANT.nullable(false), this, "");

    /**
     * The column <code>public.digital_specimen.deleted</code>.
     */
    public final TableField<DigitalSpecimenRecord, Instant> DELETED = createField(DSL.name("deleted"), SQLDataType.INSTANT, this, "");

    /**
     * The column <code>public.digital_specimen.data</code>.
     */
    public final TableField<DigitalSpecimenRecord, JSONB> DATA = createField(DSL.name("data"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.digital_specimen.original_data</code>.
     */
    public final TableField<DigitalSpecimenRecord, JSONB> ORIGINAL_DATA = createField(DSL.name("original_data"), SQLDataType.JSONB, this, "");

    private DigitalSpecimen(Name alias, Table<DigitalSpecimenRecord> aliased) {
        this(alias, aliased, null);
    }

    private DigitalSpecimen(Name alias, Table<DigitalSpecimenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.digital_specimen</code> table reference
     */
    public DigitalSpecimen(String alias) {
        this(DSL.name(alias), DIGITAL_SPECIMEN);
    }

    /**
     * Create an aliased <code>public.digital_specimen</code> table reference
     */
    public DigitalSpecimen(Name alias) {
        this(alias, DIGITAL_SPECIMEN);
    }

    /**
     * Create a <code>public.digital_specimen</code> table reference
     */
    public DigitalSpecimen() {
        this(DSL.name("digital_specimen"), null);
    }

    public <O extends Record> DigitalSpecimen(Table<O> child, ForeignKey<O, DigitalSpecimenRecord> key) {
        super(child, key, DIGITAL_SPECIMEN);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.DIGITAL_SPECIMEN_CREATED_IDX, Indexes.DIGITAL_SPECIMEN_PHYSICAL_SPECIMEN_ID_IDX);
    }

    @Override
    public UniqueKey<DigitalSpecimenRecord> getPrimaryKey() {
        return Keys.DIGITAL_SPECIMEN_PK;
    }

    @Override
    public DigitalSpecimen as(String alias) {
        return new DigitalSpecimen(DSL.name(alias), this);
    }

    @Override
    public DigitalSpecimen as(Name alias) {
        return new DigitalSpecimen(alias, this);
    }

    @Override
    public DigitalSpecimen as(Table<?> alias) {
        return new DigitalSpecimen(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DigitalSpecimen rename(String name) {
        return new DigitalSpecimen(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DigitalSpecimen rename(Name name) {
        return new DigitalSpecimen(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DigitalSpecimen rename(Table<?> name) {
        return new DigitalSpecimen(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row14 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row14<String, Integer, String, Short, String, String, String, String, String, Instant, Instant, Instant, JSONB, JSONB> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function14<? super String, ? super Integer, ? super String, ? super Short, ? super String, ? super String, ? super String, ? super String, ? super String, ? super Instant, ? super Instant, ? super Instant, ? super JSONB, ? super JSONB, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function14<? super String, ? super Integer, ? super String, ? super Short, ? super String, ? super String, ? super String, ? super String, ? super String, ? super Instant, ? super Instant, ? super Instant, ? super JSONB, ? super JSONB, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
